services:
  app:
    image: leechael/phala-cloud-python-starter:latest
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - RSA_PRIVATE_KEY_BASE64=${RSA_PRIVATE_KEY_BASE64}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - DSTACK_API_KEY=${DSTACK_API_KEY}
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /var/run/dstack.sock:/var/run/dstack.sock